; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Repercussion3"
#define MyAppVersion "1.0.0"
#define MyAppExeName "Repercussion3.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{585B011F-B17A-412C-B1E8-DB0402E4F810}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=LICENSE
InfoBeforeFile=README.md
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#SourcePath}
OutputBaseFilename=Setup {#MyAppName} v{#MyAppVersion}
SetupIconFile=data\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "target/release/{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "data\*"; DestDir: "{app}\data"; Flags: ignoreversion
Source: "allegro_acodec-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_audio-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_color-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_dialog-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_font-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_image-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_primitives-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro_ttf-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "allegro-5.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

